### ISSUE TITLE
Add Cooldown Timers (From the API) To the config. 

### ISSUE THREAD

**Issue by GoldenEdit** [LunarClient/BukkitImpl#2]
Could you add Cooldown Timers from the API into the config? 

Example Config addition:

```yml
cooldown:
    - Combat:
        name: CombatTag
        time: 30
        item: DIAMOND_SWORD
    - Ender_Pearl
        name: Teleport
        time: 8
        item: ENDER_PEARL
```
